export const techsjson = [
    { "name": "C#" },
    { "name": "Python" },
    { "name": "C++" },
    { "name": "React" },
    { "name": "PostgreSQL" },
    { "name": "MongoDB" },
    { "name": "Figma" },
    { "name": "Material UI" },
    { "name": "Graphic Design" },
    { "name": "iOS" },
    { "name": "Drupal" },
    { "name": "Laravel" },
    { "name": "MySQL" },
    { "name": "CorelDraw" },
    { "name": "Ngnix" },
    { "name": "Flask" },
    { "name": "PL/SQL" },
    { "name": "Power BI" },
    { "name": "ApolloClient" },
    { "name": "Salesforce" },
    { "name": "Truffle" },
    { "name": "Ganache" },
    { "name": "Krita" },
    { "name": "Linux" },
    { "name": "Airflow" },
    { "name": "PowerBuilder" },
    { "name": "Express" },
    { "name": "Visual Studio" },
    { "name": "Postman" },
    { "name": "Git" },
    { "name": "Data Structure" },
    { "name": "Vuex" },
    { "name": "Access" },
    { "name": "Photoshop" },
    { "name": "Illustrator" },
    { "name": "Visual Basic 6.0" },
    { "name": "Product Design" },
    { "name": "Angular" },
    { "name": "Kotlin" },
    { "name": "Rxjs" },
    { "name": "InkScape" },
    { "name": "Framer motion" },
    { "name": "Tableau" },
    { "name": "Database" },
    { "name": "Go" },
    { "name": "Next.js" },
    { "name": "Sass" },
    { "name": "Scraping" },
    { "name": "GraphQL" },
    { "name": "TypeScript" },
    { "name": "SCSS" },
    { "name": "Tailwind" },
    { "name": "Hadoop" },
    { "name": "Testing" },
    { "name": "Unity" },
    { "name": "Firebase" },
    { "name": "Node.js" },
    { "name": "Wordpress" },
    { "name": "Data Analytics" },
    { "name": "Remix" },
    { "name": "Spark" },
    { "name": "Vue.js" },
    { "name": "Redux" },
    { "name": "React Native" },
    { "name": "Docker" },
    { "name": "Data Science" },
    { "name": "Machine Learning" },
    { "name": ".NET" },
    { "name": "Google Ads" },
    { "name": "Mobile Development" },
    { "name": "Google Analytics" },
    { "name": "Google Tag Manager" },
    { "name": "Bootstrap" },
    { "name": "Apache" },
    { "name": "Nest.js" },
    { "name": "Flutter" },
    { "name": "Redis" },
    { "name": "Swagger" },
    { "name": "Pyspark" },
    { "name": "Django" },
    { "name": "SparkR" },
    { "name": "JWT" },
    { "name": "Web Design" },
    { "name": "Loopback4.js" },
    { "name": "AWS" },
    { "name": "Jest" },
    { "name": "CI/CD pipelines" },
    { "name": "Styled-Components" },
    { "name": "Scala" },
    { "name": "Ionic 2" },
    { "name": "Ruby" },
    { "name": "PHP" },
    { "name": "CSS" },
    { "name": "React.js" },
    { "name": "UX/UI Design" },
    { "name": "Sequelize" },
    { "name": "Rails" },
    { "name": "Cassandra" },
    { "name": "Java" },
    { "name": "SQL" },
    { "name": "JavaScript" },
    { "name": "Python" },
    { "name": "MongoDB" },
    { "name": "UX Research" },
    { "name": "HTML5" },
    { "name": "CSS3" },
    { "name": "WebSockets" },
    { "name": "Solidity" },
    { "name": "Hardhat" },
    { "name": "Neo4J" },
    { "name": "REST" },
    { "name": "Ether.js" },
    { "name": "NoSQL" },
    { "name": "Product Management" },
    { "name": "Adobe Experience Manager (AEM)" },
    { "name": "Mongoose" },
    { "name": "HTML" }
]

export const projectsjson = [
    {
        "title": "JUNIOR",
        "description": "proyecto grande",
        "gitHubUrl": "sinruta",
        "wspUrl": "tampoco",
        "newtech": [
                "C",
                "Python"
            ],
        "payment": true,
        "userId": "63365944ba91504b94953c98",
        "image": "nohay.jpg",
        "status": "develop"
    },
    {
        "title": "Fakebook",
        "description": "proyecto grande",
        "gitHubUrl": "sinruta",
        "wspUrl": "tampoco",
        "newtech": [
                "Javascript",
                "Python"
            ],
        "payment": true,
        "userId": "63365944ba91504b94953c98",
        "image": "nohay.jpg",
        "status": "develop"
    }
]

export const usersjson = [
    {
        "name": "Joan",
        "email": "joan.quispe@gmail.com",
        "password": "Joan1234@",
        "projects": [
                
            ],
        "collaborations": [
                
        ],
        "github": "63365944ba91504b94953c98.com",
        "puntaje": 0,
    },
    {
        "name": "Enzo",
        "email": "enzo.s@gmail.com",
        "password": "Enzo1234@",
        "projects": [
                
            ],
        "collaborations": [
                
        ],
        "github": "63365944ba91aa4b94953c98.com",
        "puntaje": 0,
    }
]

export const signinjson = [
    {
        "name": "joan",
        "email": "joan.quispe@gmail.com",
        "password": "123456",
        "confirm_password": "123456"
    },
    {
        "name": "enzo",
        "email": "enzo.s@gmail.com",
        "password": "Enzo1234@",
        "confirm_password": "Enzo1234@"
    }
] 